repositories:
  - name: nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: jenkins
    url: https://charts.jenkins.io

  - name: gitea
    url: https://dl.gitea.com/charts/

  - name: harbor
    url: https://helm.goharbor.io

  - name: sonarqube
    url: https://SonarSource.github.io/helm-chart-sonarqube

  - name: argo
    url: https://argoproj.github.io/argo-helm

  - name: empathyco
    url: https://empathyco.github.io/helm-charts/
  
  # - name: gitlab
  #   url: https://charts.gitlab.io/

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.10.0
  values:
    - values/ingress-nginx/values.yaml

- name: jenkins
  namespace: jenkins
  createNamespace: true
  chart: jenkins/jenkins
  version: 5.1.0
  values:
    - values/jenkins/values.yaml

- name: gitea
  namespace: gitea
  createNamespace: true
  chart: gitea/gitea
  version: 10.1.3
  values:
    - values/gitea/values.yaml

- name: harbor
  namespace: harbor
  createNamespace: true
  chart: harbor/harbor
  version: 1.14.0
  values:
    - values/harbor/values.yaml

- name: sonarqube
  namespace: sonarqube
  createNamespace: true
  chart: sonarqube/sonarqube
  version: 10.4.0+2288
  values:
    - values/sonarqube/values.yaml

- name: argocd
  namespace: argocd
  createNamespace: true
  chart: argo/argo-cd
  version: 6.2.5
  values:
    - values/argo-cd/values.yaml

- name: imagepullsecret-patcher
  namespace: imagepullsecret-patcher
  createNamespace: true
  chart: empathyco/imagepullsecret-patcher
  version: 1.0.0
  values:
    - values/imagepullsecret-patcher/values.yaml

# - name: gitlab
#   namespace: gitlab
#   createNamespace: true
#   chart: gitlab/gitlab
#   version: 16.9
#   values:
#     - values/gitlab/values.yaml